import { parseSegments, segmentParam, type RouteParam } from "./resolve-route-path.js";

/** One generated route file's contribution to the barrel. */
export type RouteMeta = {
  /** App-relative, posix-separated dir, e.g. "api/posts/[id]/like". */
  relDir: string;
  /** Usable verb exports (those with a ResponseMiddleware), e.g. ["POST", "GET"]. */
  verbs: string[];
  /** Ordered dynamic params along the path, e.g. [{ name: "id", type: "string", optional: false }]. */
  params: RouteParam[];
};

type TrieNode = {
  staticChildren: Map<string, TrieNode>;
  dynamic?: { param: RouteParam; node: TrieNode };
  route?: { moduleIndex: number; verbs: string[]; params: RouteParam[] };
};

const emptyNode = (): TrieNode => ({ staticChildren: new Map() });

const VALID_IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;
const key = (name: string): string => (VALID_IDENTIFIER.test(name) ? name : JSON.stringify(name));
const pad = (level: number): string => "  ".repeat(level);

/**
 * Emits the `routes` browse-by-autocomplete barrel: a nested object mirroring
 * the route tree where static segments are properties, dynamic segments are
 * positional calls (`posts(id)`), and verbs are zero-arg builders (`.post()`)
 * that reuse the file-mirrored builders. A node that is both callable and has
 * its own properties is expressed with `Object.assign`.
 */
export function buildBarrel(routes: RouteMeta[]): string {
  const sorted = [...routes].sort((a, b) => a.relDir.localeCompare(b.relDir));
  const root = emptyNode();
  const imports: string[] = [];

  sorted.forEach((route, moduleIndex) => {
    imports.push(`import * as _r${moduleIndex} from "./${route.relDir}";`);

    let node = root;
    for (const segment of parseSegments(route.relDir)) {
      if (segment.type === "static") {
        let child = node.staticChildren.get(segment.value);
        if (!child) {
          child = emptyNode();
          node.staticChildren.set(segment.value, child);
        }
        node = child;
      } else {
        if (!node.dynamic) node.dynamic = { param: segmentParam(segment)!, node: emptyNode() };
        node = node.dynamic.node;
      }
    }

    node.route = { moduleIndex, verbs: route.verbs, params: route.params };
  });

  return [
    `// GENERATED by \`next-pipe gen\` — do not edit by hand.`,
    `// Browse-by-autocomplete barrel of every generated route.`,
    ``,
    ...imports,
    ``,
    `export const routes = ${emitNode(root, 0)};`,
    ``,
  ].join("\n");
}

function emitNode(node: TrieNode, level: number): string {
  const members: string[] = [];

  for (const name of [...node.staticChildren.keys()].sort()) {
    members.push(`${key(name)}: ${emitNode(node.staticChildren.get(name)!, level + 1)}`);
  }

  if (node.route) {
    const { moduleIndex, verbs, params } = node.route;
    const arg = params.length ? `{ ${params.map((p) => p.name).join(", ")} }` : "";
    // Verbatim verbs, matching the generated modules' export names. Uppercase
    // also keeps a verb member from colliding with a lowercase static segment
    // of the same name (`app/api/get/route.ts` next to a GET on `api`).
    for (const verb of [...verbs].sort()) {
      members.push(`${verb}: () => _r${moduleIndex}.${verb}(${arg})`);
    }
  }

  const object = members.length
    ? `{\n${members.map((m) => pad(level + 1) + m).join(",\n")}\n${pad(level)}}`
    : `{}`;

  if (node.dynamic) {
    const { param } = node.dynamic;
    // Parenthesize the body so an object-literal return isn't parsed as a block.
    const arrow = `(${param.name}${param.optional ? "?" : ""}: ${param.type}) => (${emitNode(node.dynamic.node, level)})`;
    return members.length ? `Object.assign(${arrow}, ${object})` : arrow;
  }

  return object;
}
