#!/usr/bin/env node
import { existsSync, mkdirSync, readdirSync, realpathSync, rmSync, writeFileSync } from "node:fs";
import { dirname, isAbsolute, join, posix, relative, resolve, sep } from "node:path";
import { pathToFileURL } from "node:url";
import { parseArgs } from "node:util";
import ts from "typescript";
import { analyzeModule, buildProgram, parseTsconfig } from "./analyze-routes.js";
import { buildBarrel, type RouteMeta } from "./build-barrel.js";
import { resolveRoutePath } from "./resolve-route-path.js";

const COMMAND = "next-pipe gen";

/** Fully-resolved options driving a generation run. */
export type GenerateOptions = {
  /** Project root everything resolves against. Defaults to `process.cwd()`. */
  cwd: string;
  /** Absolute path to the Next.js `app/` directory. */
  appDir: string;
  /** Absolute path the generated route modules + barrel are written to. */
  outDir: string;
  /** Import specifier the generated files pull `defineRoute` from. */
  clientImport: string;
  /** Alias base the generated files import route handler types from (e.g. `@/app`). */
  routeImportBase: string;
  /** Absolute path to the tsconfig used to type-check the route handlers. */
  tsconfig: string;
};

/** Recursively collect every `route.ts`/`route.tsx` under `app/`. */
function findRouteFiles(dir: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...findRouteFiles(full));
    else if (entry.name === "route.ts" || entry.name === "route.tsx") out.push(full);
  }
  return out;
}

function generateModule(opts: GenerateOptions, relDir: string, verbs: string[]): string {
  const importSpecifier = relDir
    ? `${opts.routeImportBase}/${relDir}/route`
    : `${opts.routeImportBase}/route`;
  const { params, urlTemplate } = resolveRoutePath(relDir);

  const paramsType = params.length
    ? `{ ${params.map((p) => `${p.name}${p.optional ? "?" : ""}: ${p.type}`).join("; ")} }`
    : null;
  const backtickUrl = "`" + urlTemplate + "`";
  const destructure = params.map((p) => p.name).join(", ");
  const urlFn = params.length ? `({ ${destructure} }) => ${backtickUrl}` : `() => ${backtickUrl}`;
  const importNames = verbs.map((v) => `${v} as _${v}`).join(", ");

  const lines = [
    `// GENERATED by \`${COMMAND}\` — do not edit by hand.`,
    `// Source: ${importSpecifier}`,
    ``,
    `import { defineRoute } from "${opts.clientImport}";`,
    `import type { ${importNames} } from "${importSpecifier}";`,
    ``,
  ];

  for (const verb of verbs) {
    const lower = verb.toLowerCase();
    const typeArgs = paramsType ? `<typeof _${verb}, ${paramsType}>` : `<typeof _${verb}>`;
    lines.push(`export const ${lower} = defineRoute${typeArgs}(${urlFn}, "${lower}");`);
  }
  lines.push(``);

  return lines.join("\n");
}

/** Maps each route file to the program's source file, tolerant of path separators. */
function sourceFilesByPath(program: ts.Program): Map<string, ts.SourceFile> {
  const normalize = (p: string) => p.replace(/\\/g, "/");
  return new Map(program.getSourceFiles().map((sf) => [normalize(sf.fileName), sf]));
}

/** Runs the generation. Returns the number of route modules written. */
export function generate(opts: GenerateOptions): number {
  // Wipe previous output so removed/renamed routes never linger.
  rmSync(opts.outDir, { recursive: true, force: true });

  const routeFiles = findRouteFiles(opts.appDir);

  // Analyze through the type-checker so re-exports, function declarations, and
  // the `output` contract are all judged from real types, not source text.
  const parsed = parseTsconfig(opts.tsconfig);
  const program = buildProgram(parsed.fileNames, parsed.options);
  const checker = program.getTypeChecker();
  const byPath = sourceFilesByPath(program);

  const metas: RouteMeta[] = [];

  for (const filePath of routeFiles) {
    const relDir = relative(opts.appDir, dirname(filePath)).split(sep).join(posix.sep);
    const label = relDir || "(root)";

    const sourceFile = byPath.get(filePath.replace(/\\/g, "/"));
    if (!sourceFile) {
      console.warn(`⚠ ${label}: not part of the TypeScript program — skipped.`);
      continue;
    }

    const verbs = analyzeModule(checker, sourceFile);
    const usable = verbs.filter((v) => v.usable);
    for (const skipped of verbs.filter((v) => !v.usable)) {
      console.warn(
        `⚠ ${label}: ${skipped.name} has no response output type (missing ResponseMiddleware) — skipped.`,
      );
    }
    if (usable.length === 0) {
      if (verbs.length === 0) console.warn(`⚠ ${label}: no verb exports found — skipped.`);
      continue;
    }

    const verbNames = usable.map((v) => v.name);

    // `index.ts` is reserved for the barrel, so the root route module uses `_root.ts`.
    const targetPath = relDir
      ? join(opts.outDir, ...relDir.split(posix.sep)) + ".ts"
      : join(opts.outDir, "_root.ts");
    mkdirSync(dirname(targetPath), { recursive: true });
    writeFileSync(targetPath, generateModule(opts, relDir, verbNames));
    metas.push({
      relDir,
      verbs: verbNames,
      params: resolveRoutePath(relDir).params,
    });
    console.log(`✓ ${label} → ${relative(opts.cwd, targetPath)} (${verbNames.join(", ")})`);
  }

  const barrelPath = join(opts.outDir, "index.ts");
  mkdirSync(opts.outDir, { recursive: true });
  writeFileSync(barrelPath, buildBarrel(metas));
  console.log(`✓ barrel → ${relative(opts.cwd, barrelPath)}`);

  console.log(`\nGenerated ${metas.length} route module${metas.length === 1 ? "" : "s"} + barrel.`);
  return metas.length;
}

const HELP = `${COMMAND} — generate typed, server-free client route builders from your Next.js app/ directory.

Usage:
  ${COMMAND} [options]

Options:
  --app-dir <path>           Next.js app directory. Default: ./src/app or ./app (auto-detected).
  --out-dir <path>           Where generated modules are written. Default: <app-parent>/generated/routes.
  --client-import <spec>     Import specifier for defineRoute. Default: @flefebvre/next-pipe/client.
  --route-import-base <spec> Alias the generated files import route types from. Default: @/app.
  --tsconfig <path>          tsconfig used to type-check handlers. Default: nearest tsconfig.json.
  -h, --help                 Show this help.
`;

/** Parsed CLI flags, keyed exactly as declared in `parseArgs` below. */
type CliFlags = {
  "app-dir"?: string;
  "out-dir"?: string;
  "client-import"?: string;
  "route-import-base"?: string;
  tsconfig?: string;
  help?: boolean;
};

const asPath = (cwd: string, value: string) => (isAbsolute(value) ? value : resolve(cwd, value));

/** Resolves CLI flags + defaults into fully-qualified options, or exits on error. */
function resolveOptions(flags: CliFlags, cwd: string): GenerateOptions {
  const appDir = flags["app-dir"]
    ? asPath(cwd, flags["app-dir"])
    : [join(cwd, "src", "app"), join(cwd, "app")].find((p) => existsSync(p));

  if (!appDir || !existsSync(appDir)) {
    console.error(`✗ app directory not found (looked for ./src/app and ./app). Pass --app-dir.`);
    process.exit(1);
  }

  // Default output sits beside `app/`: src/app → src/generated/routes, app → generated/routes.
  const outDir = flags["out-dir"]
    ? asPath(cwd, flags["out-dir"])
    : join(dirname(appDir), "generated", "routes");

  const tsconfig = flags["tsconfig"]
    ? asPath(cwd, flags["tsconfig"])
    : ts.findConfigFile(cwd, ts.sys.fileExists, "tsconfig.json");

  if (!tsconfig || !existsSync(tsconfig)) {
    console.error(`✗ tsconfig.json not found from ${cwd}. Pass --tsconfig.`);
    process.exit(1);
  }

  return {
    cwd,
    appDir,
    outDir,
    clientImport: flags["client-import"] ?? "@flefebvre/next-pipe/client",
    routeImportBase: flags["route-import-base"] ?? "@/app",
    tsconfig,
  };
}

function runCli(argv: string[]): void {
  let flags: CliFlags;
  try {
    ({ values: flags } = parseArgs({
      args: argv,
      allowPositionals: true, // tolerate an explicit `gen` subcommand
      options: {
        "app-dir": { type: "string" },
        "out-dir": { type: "string" },
        "client-import": { type: "string" },
        "route-import-base": { type: "string" },
        tsconfig: { type: "string" },
        help: { type: "boolean", short: "h" },
      },
    }));
  } catch (err) {
    console.error(`✗ ${(err as Error).message}`);
    console.error(`\nRun \`${COMMAND} --help\` for usage.`);
    process.exit(1);
  }

  if (flags.help) {
    console.log(HELP);
    return;
  }
  generate(resolveOptions(flags, process.cwd()));
}

// Only run when invoked as the CLI entry, not when imported (e.g. by tests).
// Resolve symlinks before comparing: under pnpm/`pnpm link` the package dir is a
// symlink, so `process.argv[1]` (as invoked) and `import.meta.url` (realpath) differ.
function isCliEntry(): boolean {
  const entry = process.argv[1];
  if (!entry) return false;
  try {
    return import.meta.url === pathToFileURL(realpathSync(entry)).href;
  } catch {
    return false;
  }
}

if (isCliEntry()) {
  runCli(process.argv.slice(2));
}
